#!/usr/bin/env python3
"""Justificacion de la logica de barreras basada en datos."""

print("=" * 70)
print("DATOS PARA JUSTIFICAR LOGICA DE BARRERAS")
print("=" * 70)

print()
print("1. DISTRIBUCION DE GAPS POR BARRERA (v4):")
print("   STRONG (>20%):     132 barreras -> gap real = 36.9% promedio")
print("   MODERATE (10-20%):  54 barreras -> gap real = 15.1% promedio")
print("   WEAK (5-10%):       46 barreras -> gap real = 7.4% promedio")
print("   NONE (<5%):         56 barreras -> gap real = 1.9% promedio")

print()
print("2. GAPS PARA NUESTRAS 9 PROPIEDADES:")
print("   Ayacucho:       gap = -34.0% (cross MAS caro)")
print("   Vera Mujica:    gap = -14.1% (cross MAS caro)")
print("   P1200:          gap = -6.0%  (cross MAS caro)")
print("   Cochabamba 45:  gap = -11.9% (cross MAS caro)")
print("   Brown 2750:     sin cross")
print("   Francia 250b:   sin cross")
print("   Mabel:          sin cross")
print("   Entre Rios:     sin cross")
print("   Mitre1473:      sin cross")

print()
print("3. PATRON DETECTADO:")
print("   - 4 de 5 propiedades con cross: gap NEGATIVO")
print("   - Esto significa: cross = zona premium (no mas barata)")
print("   - La barrera detectada NO es la que esperamos")

print()
print("4. JUSTIFICACION POR COMPONENTE:")
print()
print("   ALPHA (basado en gap):")
print("   - gap < -10%:  alpha = 1.0 (excluir cross, zona diferente)")
print("   - gap > 20%:   alpha = 0.85 (cross mas barato, mas peso a same)")
print("   - otro:        alpha = f(n_same) [actual]")
print()
print("   BLEND:")
print("   - Solo aplica cuando gap esta entre -10% y +20%")
print("   - Fuera de ese rango, usar solo P33_same")
print()
print("   PENALTY (basado en gap):")
print("   - gap < -10%:  penalty = 0% (cross mas caro, no penalizar)")
print("   - gap > 20%:   penalty = (n_cross/n_total) x 0.03")
print("   - otro:        penalty = 0% (compatibles)")
print()
print("5. EJEMPLOS CONCRETOS:")
print()
print("   Ayacucho (gap = -34.0%):")
print("   - Actual: vm2 = 0.70x983 + 0.30x1182 = 942, penalty 3% = 914")
print("   - Nuevo:  vm2 = P33_same = 983 (excluir cross)")
print("   - Diferencia: +7.3%")
print()
print("   Cochabamba 45 (gap = -11.9%):")
print("   - Actual: vm2 = 0.55x755 + 0.45x980 = 856, penalty 3% = 830")
print("   - Nuevo:  vm2 = P33_same = 755 (excluir cross)")
print("   - Diferencia: -9.0%")
print()
print("   Brown 2750 (sin cross):")
print("   - Actual: vm2 = P33_same = 2176")
print("   - Nuevo:  vm2 = P33_same = 2176 (sin cambio)")
