"""
50 inmobiliarias adicionales de Rosario (no duplicadas con la lista original).
"""
INMOBILIARIAS_EXTRA = [
    {"nombre": "Vanzini Propiedades", "url": "https://www.vanzini.com.ar", "list_url": "https://www.vanzini.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Imperia Propiedades", "url": "https://www.imperiapropiedades.com", "list_url": "https://www.imperiapropiedades.com/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Dunod Propiedades", "url": "https://dunod.com.ar", "list_url": "https://dunod.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Dagostino Ferrari", "url": "https://www.dagostinoferrari.com.ar", "list_url": "https://www.dagostinoferrari.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Bertollo Propiedades", "url": "https://www.bertollo.com.ar", "list_url": "https://www.bertollo.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Beltrán Inmobiliaria", "url": "https://www.beltraninmobiliaria.com.ar", "list_url": "https://www.beltraninmobiliaria.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Lux Propiedades", "url": "https://luxpropiedades.com", "list_url": "https://luxpropiedades.com/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Criscenti Inmobiliaria", "url": "https://www.criscenti.com.ar", "list_url": "https://www.criscenti.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "ABA Propiedades", "url": "https://www.abapropiedades.com.ar", "list_url": "https://www.abapropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Borsatto Inmobiliaria", "url": "https://www.borsatto.com", "list_url": "https://www.borsatto.com/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Grupo Ambito SRL", "url": "https://www.grupoambito.com.ar", "list_url": "https://www.grupoambito.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Pilay Inmobiliaria", "url": "https://www.pilay.com.ar", "list_url": "https://www.pilay.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Avalon Propiedades", "url": "https://www.avalonpropiedades.com.ar", "list_url": "https://www.avalonpropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Marcos Abiad Propiedades", "url": "https://www.mapropiedades.com.ar", "list_url": "https://www.mapropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Rosario New Habitat", "url": "https://www.rosarionewhabitat.com.ar", "list_url": "https://www.rosarionewhabitat.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Crestale Propiedades", "url": "https://www.crestalepropiedades.com.ar", "list_url": "https://www.crestalepropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Ruiz Bienes Raíces", "url": "https://www.ruizbienesraices.com.ar", "list_url": "https://www.ruizbienesraices.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Beatriz Bienes Raíces", "url": "https://www.beatrizbienesraices.com.ar", "list_url": "https://www.beatrizbienesraices.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "ARCA Consultora Inmobiliaria", "url": "https://www.arcaconsultora.com.ar", "list_url": "https://www.arcaconsultora.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Cuini Propiedades", "url": "https://www.cuinipropiedades.com.ar", "list_url": "https://www.cuinipropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Departamentos Rosario", "url": "https://www.departamentosrosario.com", "list_url": "https://www.departamentosrosario.com/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Allegri & Lopez Maraver Propiedades", "url": "https://www.allegripropiedades.com.ar", "list_url": "https://www.allegripropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Guillermet Inmobiliaria", "url": "https://www.guillermetinmobiliaria.com.ar", "list_url": "https://www.guillermetinmobiliaria.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Remax Rosario", "url": "https://www.remax.com.ar/oficinas-rosario", "list_url": "https://www.remax.com.ar/propiedades-en-rosario", "engine": "playwright", "detail_link_selector": "a[href*='/propiedades/']"},
    {"nombre": "Century 21 Rosario", "url": "https://www.century21.com.ar", "list_url": "https://www.century21.com.ar/propiedades?ciudad=rosario", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Toribio Achával (nacional)", "url": "https://www.toribioachaval.com", "list_url": "https://www.toribioachaval.com/propiedades?ciudad=rosario", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Cabrera Propiedades", "url": "https://www.cabrerapropiedades.com.ar", "list_url": "https://www.cabrerapropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Novahaus Propiedades", "url": "https://www.novahaus.com.ar", "list_url": "https://www.novahaus.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Alianza Propiedades", "url": "https://www.alianzapropiedades.com.ar", "list_url": "https://www.alianzapropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Inmobiliaria Coria", "url": "https://www.inmobiliariacoria.com.ar", "list_url": "https://www.inmobiliariacoria.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Dominium Propiedades", "url": "https://www.dominiumpropiedades.com.ar", "list_url": "https://www.dominiumpropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Prieto Propiedades", "url": "https://www.prietopropiedades.com.ar", "list_url": "https://www.prietopropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Moretti Propiedades", "url": "https://www.morettipropiedades.com.ar", "list_url": "https://www.morettipropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Del Bono Propiedades", "url": "https://www.delbonopropiedades.com.ar", "list_url": "https://www.delbonopropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Gallo Propiedades", "url": "https://www.gallopropiedades.com.ar", "list_url": "https://www.gallopropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Amico Propiedades", "url": "https://www.amicopropiedades.com.ar", "list_url": "https://www.amicopropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Parodi Propiedades", "url": "https://www.parodipropiedades.com.ar", "list_url": "https://www.parodipropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Pagliero Propiedades", "url": "https://www.paglieropropiedades.com.ar", "list_url": "https://www.paglieropropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Palermo Propiedades Rosario", "url": "https://www.palermopropiedades.com.ar", "list_url": "https://www.palermopropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Rossi Propiedades", "url": "https://www.rossipropiedades.com.ar", "list_url": "https://www.rossipropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Espósito Propiedades", "url": "https://www.espositopropiedades.com.ar", "list_url": "https://www.espositopropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Franco Propiedades", "url": "https://www.francopropiedades.com.ar", "list_url": "https://www.francopropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Colombo Propiedades", "url": "https://www.colombropropiedades.com.ar", "list_url": "https://www.colombropropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Biasotti Propiedades", "url": "https://www.biasottipropiedades.com.ar", "list_url": "https://www.biasottipropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Santoro Propiedades", "url": "https://www.santoropropiedades.com.ar", "list_url": "https://www.santoropropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Rivero Propiedades", "url": "https://www.riveropropiedades.com.ar", "list_url": "https://www.riveropropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Montes Propiedades", "url": "https://www.montespropiedades.com.ar", "list_url": "https://www.montespropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Nobile Propiedades", "url": "https://www.nobilepropiedades.com.ar", "list_url": "https://www.nobilepropiedades.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Almada Propiedades", "url": "https://www.almadapropiedades.com.ar", "list_url": "https://www.almadapropiedades.com.ar/propiedades", "engine": "http", "detail_link_selector": "a[href*='/propiedad']"},
    {"nombre": "Propia COCIR", "url": "https://propia.com.ar", "list_url": "https://propia.com.ar/propiedades", "engine": "playwright", "detail_link_selector": "a[href*='/propiedad'], a.property-link"},
]
